[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/tiktok/auth"
  to = "/.netlify/functions/tiktok-auth"
  status = 200

[[redirects]]
  from = "/api/tiktok/video/*"
  to = "/.netlify/functions/tiktok-video/:splat"
  status = 200

[[redirects]]
  from = "/api/apify"
  to = "/.netlify/functions/apify-proxy"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200